// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface ArtworkResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ArtworkResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.Artwork artworks = 1;</code>
   */
  java.util.List<proto.Artwork> 
      getArtworksList();
  /**
   * <code>repeated .proto.Artwork artworks = 1;</code>
   */
  proto.Artwork getArtworks(int index);
  /**
   * <code>repeated .proto.Artwork artworks = 1;</code>
   */
  int getArtworksCount();
  /**
   * <code>repeated .proto.Artwork artworks = 1;</code>
   */
  java.util.List<? extends proto.ArtworkOrBuilder> 
      getArtworksOrBuilderList();
  /**
   * <code>repeated .proto.Artwork artworks = 1;</code>
   */
  proto.ArtworkOrBuilder getArtworksOrBuilder(
      int index);
}
