// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface CharacterResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.CharacterResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.Character characters = 1;</code>
   */
  java.util.List<proto.Character> 
      getCharactersList();
  /**
   * <code>repeated .proto.Character characters = 1;</code>
   */
  proto.Character getCharacters(int index);
  /**
   * <code>repeated .proto.Character characters = 1;</code>
   */
  int getCharactersCount();
  /**
   * <code>repeated .proto.Character characters = 1;</code>
   */
  java.util.List<? extends proto.CharacterOrBuilder> 
      getCharactersOrBuilderList();
  /**
   * <code>repeated .proto.Character characters = 1;</code>
   */
  proto.CharacterOrBuilder getCharactersOrBuilder(
      int index);
}
