// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface CharacterMugShotResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.CharacterMugShotResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.CharacterMugShot charactermugshots = 1;</code>
   */
  java.util.List<proto.CharacterMugShot> 
      getCharactermugshotsList();
  /**
   * <code>repeated .proto.CharacterMugShot charactermugshots = 1;</code>
   */
  proto.CharacterMugShot getCharactermugshots(int index);
  /**
   * <code>repeated .proto.CharacterMugShot charactermugshots = 1;</code>
   */
  int getCharactermugshotsCount();
  /**
   * <code>repeated .proto.CharacterMugShot charactermugshots = 1;</code>
   */
  java.util.List<? extends proto.CharacterMugShotOrBuilder> 
      getCharactermugshotsOrBuilderList();
  /**
   * <code>repeated .proto.CharacterMugShot charactermugshots = 1;</code>
   */
  proto.CharacterMugShotOrBuilder getCharactermugshotsOrBuilder(
      int index);
}
