// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface CollectionResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.CollectionResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.Collection collections = 1;</code>
   */
  java.util.List<proto.Collection> 
      getCollectionsList();
  /**
   * <code>repeated .proto.Collection collections = 1;</code>
   */
  proto.Collection getCollections(int index);
  /**
   * <code>repeated .proto.Collection collections = 1;</code>
   */
  int getCollectionsCount();
  /**
   * <code>repeated .proto.Collection collections = 1;</code>
   */
  java.util.List<? extends proto.CollectionOrBuilder> 
      getCollectionsOrBuilderList();
  /**
   * <code>repeated .proto.Collection collections = 1;</code>
   */
  proto.CollectionOrBuilder getCollectionsOrBuilder(
      int index);
}
