// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface CollectionRelationTypeResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.CollectionRelationTypeResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.CollectionRelationType collectionrelationtypes = 1;</code>
   */
  java.util.List<proto.CollectionRelationType> 
      getCollectionrelationtypesList();
  /**
   * <code>repeated .proto.CollectionRelationType collectionrelationtypes = 1;</code>
   */
  proto.CollectionRelationType getCollectionrelationtypes(int index);
  /**
   * <code>repeated .proto.CollectionRelationType collectionrelationtypes = 1;</code>
   */
  int getCollectionrelationtypesCount();
  /**
   * <code>repeated .proto.CollectionRelationType collectionrelationtypes = 1;</code>
   */
  java.util.List<? extends proto.CollectionRelationTypeOrBuilder> 
      getCollectionrelationtypesOrBuilderList();
  /**
   * <code>repeated .proto.CollectionRelationType collectionrelationtypes = 1;</code>
   */
  proto.CollectionRelationTypeOrBuilder getCollectionrelationtypesOrBuilder(
      int index);
}
