// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface CollectionTypeResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.CollectionTypeResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.CollectionType collectiontypes = 1;</code>
   */
  java.util.List<proto.CollectionType> 
      getCollectiontypesList();
  /**
   * <code>repeated .proto.CollectionType collectiontypes = 1;</code>
   */
  proto.CollectionType getCollectiontypes(int index);
  /**
   * <code>repeated .proto.CollectionType collectiontypes = 1;</code>
   */
  int getCollectiontypesCount();
  /**
   * <code>repeated .proto.CollectionType collectiontypes = 1;</code>
   */
  java.util.List<? extends proto.CollectionTypeOrBuilder> 
      getCollectiontypesOrBuilderList();
  /**
   * <code>repeated .proto.CollectionType collectiontypes = 1;</code>
   */
  proto.CollectionTypeOrBuilder getCollectiontypesOrBuilder(
      int index);
}
