// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface CompanyWebsiteResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.CompanyWebsiteResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.CompanyWebsite companywebsites = 1;</code>
   */
  java.util.List<proto.CompanyWebsite> 
      getCompanywebsitesList();
  /**
   * <code>repeated .proto.CompanyWebsite companywebsites = 1;</code>
   */
  proto.CompanyWebsite getCompanywebsites(int index);
  /**
   * <code>repeated .proto.CompanyWebsite companywebsites = 1;</code>
   */
  int getCompanywebsitesCount();
  /**
   * <code>repeated .proto.CompanyWebsite companywebsites = 1;</code>
   */
  java.util.List<? extends proto.CompanyWebsiteOrBuilder> 
      getCompanywebsitesOrBuilderList();
  /**
   * <code>repeated .proto.CompanyWebsite companywebsites = 1;</code>
   */
  proto.CompanyWebsiteOrBuilder getCompanywebsitesOrBuilder(
      int index);
}
