// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface EventNetworkResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.EventNetworkResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.EventNetwork eventnetworks = 1;</code>
   */
  java.util.List<proto.EventNetwork> 
      getEventnetworksList();
  /**
   * <code>repeated .proto.EventNetwork eventnetworks = 1;</code>
   */
  proto.EventNetwork getEventnetworks(int index);
  /**
   * <code>repeated .proto.EventNetwork eventnetworks = 1;</code>
   */
  int getEventnetworksCount();
  /**
   * <code>repeated .proto.EventNetwork eventnetworks = 1;</code>
   */
  java.util.List<? extends proto.EventNetworkOrBuilder> 
      getEventnetworksOrBuilderList();
  /**
   * <code>repeated .proto.EventNetwork eventnetworks = 1;</code>
   */
  proto.EventNetworkOrBuilder getEventnetworksOrBuilder(
      int index);
}
