// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface FranchiseResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.FranchiseResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.Franchise franchises = 1;</code>
   */
  java.util.List<proto.Franchise> 
      getFranchisesList();
  /**
   * <code>repeated .proto.Franchise franchises = 1;</code>
   */
  proto.Franchise getFranchises(int index);
  /**
   * <code>repeated .proto.Franchise franchises = 1;</code>
   */
  int getFranchisesCount();
  /**
   * <code>repeated .proto.Franchise franchises = 1;</code>
   */
  java.util.List<? extends proto.FranchiseOrBuilder> 
      getFranchisesOrBuilderList();
  /**
   * <code>repeated .proto.Franchise franchises = 1;</code>
   */
  proto.FranchiseOrBuilder getFranchisesOrBuilder(
      int index);
}
