// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface GameEngineLogoResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GameEngineLogoResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.GameEngineLogo gameenginelogos = 1;</code>
   */
  java.util.List<proto.GameEngineLogo> 
      getGameenginelogosList();
  /**
   * <code>repeated .proto.GameEngineLogo gameenginelogos = 1;</code>
   */
  proto.GameEngineLogo getGameenginelogos(int index);
  /**
   * <code>repeated .proto.GameEngineLogo gameenginelogos = 1;</code>
   */
  int getGameenginelogosCount();
  /**
   * <code>repeated .proto.GameEngineLogo gameenginelogos = 1;</code>
   */
  java.util.List<? extends proto.GameEngineLogoOrBuilder> 
      getGameenginelogosOrBuilderList();
  /**
   * <code>repeated .proto.GameEngineLogo gameenginelogos = 1;</code>
   */
  proto.GameEngineLogoOrBuilder getGameenginelogosOrBuilder(
      int index);
}
