// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface GameVideoResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GameVideoResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.GameVideo gamevideos = 1;</code>
   */
  java.util.List<proto.GameVideo> 
      getGamevideosList();
  /**
   * <code>repeated .proto.GameVideo gamevideos = 1;</code>
   */
  proto.GameVideo getGamevideos(int index);
  /**
   * <code>repeated .proto.GameVideo gamevideos = 1;</code>
   */
  int getGamevideosCount();
  /**
   * <code>repeated .proto.GameVideo gamevideos = 1;</code>
   */
  java.util.List<? extends proto.GameVideoOrBuilder> 
      getGamevideosOrBuilderList();
  /**
   * <code>repeated .proto.GameVideo gamevideos = 1;</code>
   */
  proto.GameVideoOrBuilder getGamevideosOrBuilder(
      int index);
}
