// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface GenreResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GenreResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.Genre genres = 1;</code>
   */
  java.util.List<proto.Genre> 
      getGenresList();
  /**
   * <code>repeated .proto.Genre genres = 1;</code>
   */
  proto.Genre getGenres(int index);
  /**
   * <code>repeated .proto.Genre genres = 1;</code>
   */
  int getGenresCount();
  /**
   * <code>repeated .proto.Genre genres = 1;</code>
   */
  java.util.List<? extends proto.GenreOrBuilder> 
      getGenresOrBuilderList();
  /**
   * <code>repeated .proto.Genre genres = 1;</code>
   */
  proto.GenreOrBuilder getGenresOrBuilder(
      int index);
}
