// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface KeywordResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.KeywordResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.Keyword keywords = 1;</code>
   */
  java.util.List<proto.Keyword> 
      getKeywordsList();
  /**
   * <code>repeated .proto.Keyword keywords = 1;</code>
   */
  proto.Keyword getKeywords(int index);
  /**
   * <code>repeated .proto.Keyword keywords = 1;</code>
   */
  int getKeywordsCount();
  /**
   * <code>repeated .proto.Keyword keywords = 1;</code>
   */
  java.util.List<? extends proto.KeywordOrBuilder> 
      getKeywordsOrBuilderList();
  /**
   * <code>repeated .proto.Keyword keywords = 1;</code>
   */
  proto.KeywordOrBuilder getKeywordsOrBuilder(
      int index);
}
