// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface LanguageSupportTypeResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.LanguageSupportTypeResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.LanguageSupportType languagesupporttypes = 1;</code>
   */
  java.util.List<proto.LanguageSupportType> 
      getLanguagesupporttypesList();
  /**
   * <code>repeated .proto.LanguageSupportType languagesupporttypes = 1;</code>
   */
  proto.LanguageSupportType getLanguagesupporttypes(int index);
  /**
   * <code>repeated .proto.LanguageSupportType languagesupporttypes = 1;</code>
   */
  int getLanguagesupporttypesCount();
  /**
   * <code>repeated .proto.LanguageSupportType languagesupporttypes = 1;</code>
   */
  java.util.List<? extends proto.LanguageSupportTypeOrBuilder> 
      getLanguagesupporttypesOrBuilderList();
  /**
   * <code>repeated .proto.LanguageSupportType languagesupporttypes = 1;</code>
   */
  proto.LanguageSupportTypeOrBuilder getLanguagesupporttypesOrBuilder(
      int index);
}
