// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface LanguageResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.LanguageResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.Language languages = 1;</code>
   */
  java.util.List<proto.Language> 
      getLanguagesList();
  /**
   * <code>repeated .proto.Language languages = 1;</code>
   */
  proto.Language getLanguages(int index);
  /**
   * <code>repeated .proto.Language languages = 1;</code>
   */
  int getLanguagesCount();
  /**
   * <code>repeated .proto.Language languages = 1;</code>
   */
  java.util.List<? extends proto.LanguageOrBuilder> 
      getLanguagesOrBuilderList();
  /**
   * <code>repeated .proto.Language languages = 1;</code>
   */
  proto.LanguageOrBuilder getLanguagesOrBuilder(
      int index);
}
