// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface LanguageSupportResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.LanguageSupportResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.LanguageSupport languagesupports = 1;</code>
   */
  java.util.List<proto.LanguageSupport> 
      getLanguagesupportsList();
  /**
   * <code>repeated .proto.LanguageSupport languagesupports = 1;</code>
   */
  proto.LanguageSupport getLanguagesupports(int index);
  /**
   * <code>repeated .proto.LanguageSupport languagesupports = 1;</code>
   */
  int getLanguagesupportsCount();
  /**
   * <code>repeated .proto.LanguageSupport languagesupports = 1;</code>
   */
  java.util.List<? extends proto.LanguageSupportOrBuilder> 
      getLanguagesupportsOrBuilderList();
  /**
   * <code>repeated .proto.LanguageSupport languagesupports = 1;</code>
   */
  proto.LanguageSupportOrBuilder getLanguagesupportsOrBuilder(
      int index);
}
