// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface NetworkTypeResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.NetworkTypeResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.NetworkType networktypes = 1;</code>
   */
  java.util.List<proto.NetworkType> 
      getNetworktypesList();
  /**
   * <code>repeated .proto.NetworkType networktypes = 1;</code>
   */
  proto.NetworkType getNetworktypes(int index);
  /**
   * <code>repeated .proto.NetworkType networktypes = 1;</code>
   */
  int getNetworktypesCount();
  /**
   * <code>repeated .proto.NetworkType networktypes = 1;</code>
   */
  java.util.List<? extends proto.NetworkTypeOrBuilder> 
      getNetworktypesOrBuilderList();
  /**
   * <code>repeated .proto.NetworkType networktypes = 1;</code>
   */
  proto.NetworkTypeOrBuilder getNetworktypesOrBuilder(
      int index);
}
