// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface PlatformWebsiteResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.PlatformWebsiteResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.PlatformWebsite platformwebsites = 1;</code>
   */
  java.util.List<proto.PlatformWebsite> 
      getPlatformwebsitesList();
  /**
   * <code>repeated .proto.PlatformWebsite platformwebsites = 1;</code>
   */
  proto.PlatformWebsite getPlatformwebsites(int index);
  /**
   * <code>repeated .proto.PlatformWebsite platformwebsites = 1;</code>
   */
  int getPlatformwebsitesCount();
  /**
   * <code>repeated .proto.PlatformWebsite platformwebsites = 1;</code>
   */
  java.util.List<? extends proto.PlatformWebsiteOrBuilder> 
      getPlatformwebsitesOrBuilderList();
  /**
   * <code>repeated .proto.PlatformWebsite platformwebsites = 1;</code>
   */
  proto.PlatformWebsiteOrBuilder getPlatformwebsitesOrBuilder(
      int index);
}
