// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface PlatformResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.PlatformResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.Platform platforms = 1;</code>
   */
  java.util.List<proto.Platform> 
      getPlatformsList();
  /**
   * <code>repeated .proto.Platform platforms = 1;</code>
   */
  proto.Platform getPlatforms(int index);
  /**
   * <code>repeated .proto.Platform platforms = 1;</code>
   */
  int getPlatformsCount();
  /**
   * <code>repeated .proto.Platform platforms = 1;</code>
   */
  java.util.List<? extends proto.PlatformOrBuilder> 
      getPlatformsOrBuilderList();
  /**
   * <code>repeated .proto.Platform platforms = 1;</code>
   */
  proto.PlatformOrBuilder getPlatformsOrBuilder(
      int index);
}
