// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface PlatformFamilyResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.PlatformFamilyResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.PlatformFamily platformfamilies = 1;</code>
   */
  java.util.List<proto.PlatformFamily> 
      getPlatformfamiliesList();
  /**
   * <code>repeated .proto.PlatformFamily platformfamilies = 1;</code>
   */
  proto.PlatformFamily getPlatformfamilies(int index);
  /**
   * <code>repeated .proto.PlatformFamily platformfamilies = 1;</code>
   */
  int getPlatformfamiliesCount();
  /**
   * <code>repeated .proto.PlatformFamily platformfamilies = 1;</code>
   */
  java.util.List<? extends proto.PlatformFamilyOrBuilder> 
      getPlatformfamiliesOrBuilderList();
  /**
   * <code>repeated .proto.PlatformFamily platformfamilies = 1;</code>
   */
  proto.PlatformFamilyOrBuilder getPlatformfamiliesOrBuilder(
      int index);
}
