// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface PlayerPerspectiveResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.PlayerPerspectiveResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.PlayerPerspective playerperspectives = 1;</code>
   */
  java.util.List<proto.PlayerPerspective> 
      getPlayerperspectivesList();
  /**
   * <code>repeated .proto.PlayerPerspective playerperspectives = 1;</code>
   */
  proto.PlayerPerspective getPlayerperspectives(int index);
  /**
   * <code>repeated .proto.PlayerPerspective playerperspectives = 1;</code>
   */
  int getPlayerperspectivesCount();
  /**
   * <code>repeated .proto.PlayerPerspective playerperspectives = 1;</code>
   */
  java.util.List<? extends proto.PlayerPerspectiveOrBuilder> 
      getPlayerperspectivesOrBuilderList();
  /**
   * <code>repeated .proto.PlayerPerspective playerperspectives = 1;</code>
   */
  proto.PlayerPerspectiveOrBuilder getPlayerperspectivesOrBuilder(
      int index);
}
