// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

/**
 * Protobuf type {@code proto.PopularityPrimitiveResult}
 */
public final class PopularityPrimitiveResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:proto.PopularityPrimitiveResult)
    PopularityPrimitiveResultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      PopularityPrimitiveResult.class.getName());
  }
  // Use PopularityPrimitiveResult.newBuilder() to construct.
  private PopularityPrimitiveResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PopularityPrimitiveResult() {
    popularityprimitives_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.Igdbapi.internal_static_proto_PopularityPrimitiveResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.Igdbapi.internal_static_proto_PopularityPrimitiveResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.PopularityPrimitiveResult.class, proto.PopularityPrimitiveResult.Builder.class);
  }

  public static final int POPULARITYPRIMITIVES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<proto.PopularityPrimitive> popularityprimitives_;
  /**
   * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
   */
  @java.lang.Override
  public java.util.List<proto.PopularityPrimitive> getPopularityprimitivesList() {
    return popularityprimitives_;
  }
  /**
   * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends proto.PopularityPrimitiveOrBuilder> 
      getPopularityprimitivesOrBuilderList() {
    return popularityprimitives_;
  }
  /**
   * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
   */
  @java.lang.Override
  public int getPopularityprimitivesCount() {
    return popularityprimitives_.size();
  }
  /**
   * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
   */
  @java.lang.Override
  public proto.PopularityPrimitive getPopularityprimitives(int index) {
    return popularityprimitives_.get(index);
  }
  /**
   * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
   */
  @java.lang.Override
  public proto.PopularityPrimitiveOrBuilder getPopularityprimitivesOrBuilder(
      int index) {
    return popularityprimitives_.get(index);
  }

  public static proto.PopularityPrimitiveResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.PopularityPrimitiveResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.PopularityPrimitiveResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.PopularityPrimitiveResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.PopularityPrimitiveResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.PopularityPrimitiveResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.PopularityPrimitiveResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static proto.PopularityPrimitiveResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static proto.PopularityPrimitiveResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static proto.PopularityPrimitiveResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.PopularityPrimitiveResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static proto.PopularityPrimitiveResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.PopularityPrimitiveResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.PopularityPrimitiveResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.PopularityPrimitiveResult)
      proto.PopularityPrimitiveResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Igdbapi.internal_static_proto_PopularityPrimitiveResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Igdbapi.internal_static_proto_PopularityPrimitiveResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.PopularityPrimitiveResult.class, proto.PopularityPrimitiveResult.Builder.class);
    }

    // Construct using proto.PopularityPrimitiveResult.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (popularityprimitivesBuilder_ == null) {
        popularityprimitives_ = java.util.Collections.emptyList();
      } else {
        popularityprimitives_ = null;
        popularityprimitivesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.Igdbapi.internal_static_proto_PopularityPrimitiveResult_descriptor;
    }

    @java.lang.Override
    public proto.PopularityPrimitiveResult getDefaultInstanceForType() {
      return proto.PopularityPrimitiveResult.getDefaultInstance();
    }

    @java.lang.Override
    public proto.PopularityPrimitiveResult build() {
      proto.PopularityPrimitiveResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.PopularityPrimitiveResult buildPartial() {
      proto.PopularityPrimitiveResult result = new proto.PopularityPrimitiveResult(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(proto.PopularityPrimitiveResult result) {
      if (popularityprimitivesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          popularityprimitives_ = java.util.Collections.unmodifiableList(popularityprimitives_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.popularityprimitives_ = popularityprimitives_;
      } else {
        result.popularityprimitives_ = popularityprimitivesBuilder_.build();
      }
    }

    private void buildPartial0(proto.PopularityPrimitiveResult result) {
      int from_bitField0_ = bitField0_;
    }

    private int bitField0_;

    private java.util.List<proto.PopularityPrimitive> popularityprimitives_ =
      java.util.Collections.emptyList();
    private void ensurePopularityprimitivesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        popularityprimitives_ = new java.util.ArrayList<proto.PopularityPrimitive>(popularityprimitives_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        proto.PopularityPrimitive, proto.PopularityPrimitive.Builder, proto.PopularityPrimitiveOrBuilder> popularityprimitivesBuilder_;

    /**
     * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
     */
    public java.util.List<proto.PopularityPrimitive> getPopularityprimitivesList() {
      if (popularityprimitivesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(popularityprimitives_);
      } else {
        return popularityprimitivesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
     */
    public int getPopularityprimitivesCount() {
      if (popularityprimitivesBuilder_ == null) {
        return popularityprimitives_.size();
      } else {
        return popularityprimitivesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
     */
    public proto.PopularityPrimitive getPopularityprimitives(int index) {
      if (popularityprimitivesBuilder_ == null) {
        return popularityprimitives_.get(index);
      } else {
        return popularityprimitivesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
     */
    public Builder setPopularityprimitives(
        int index, proto.PopularityPrimitive value) {
      if (popularityprimitivesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePopularityprimitivesIsMutable();
        popularityprimitives_.set(index, value);
        onChanged();
      } else {
        popularityprimitivesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
     */
    public Builder setPopularityprimitives(
        int index, proto.PopularityPrimitive.Builder builderForValue) {
      if (popularityprimitivesBuilder_ == null) {
        ensurePopularityprimitivesIsMutable();
        popularityprimitives_.set(index, builderForValue.build());
        onChanged();
      } else {
        popularityprimitivesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
     */
    public Builder addPopularityprimitives(proto.PopularityPrimitive value) {
      if (popularityprimitivesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePopularityprimitivesIsMutable();
        popularityprimitives_.add(value);
        onChanged();
      } else {
        popularityprimitivesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
     */
    public Builder addPopularityprimitives(
        int index, proto.PopularityPrimitive value) {
      if (popularityprimitivesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePopularityprimitivesIsMutable();
        popularityprimitives_.add(index, value);
        onChanged();
      } else {
        popularityprimitivesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
     */
    public Builder addPopularityprimitives(
        proto.PopularityPrimitive.Builder builderForValue) {
      if (popularityprimitivesBuilder_ == null) {
        ensurePopularityprimitivesIsMutable();
        popularityprimitives_.add(builderForValue.build());
        onChanged();
      } else {
        popularityprimitivesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
     */
    public Builder addPopularityprimitives(
        int index, proto.PopularityPrimitive.Builder builderForValue) {
      if (popularityprimitivesBuilder_ == null) {
        ensurePopularityprimitivesIsMutable();
        popularityprimitives_.add(index, builderForValue.build());
        onChanged();
      } else {
        popularityprimitivesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
     */
    public Builder addAllPopularityprimitives(
        java.lang.Iterable<? extends proto.PopularityPrimitive> values) {
      if (popularityprimitivesBuilder_ == null) {
        ensurePopularityprimitivesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, popularityprimitives_);
        onChanged();
      } else {
        popularityprimitivesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
     */
    public Builder clearPopularityprimitives() {
      if (popularityprimitivesBuilder_ == null) {
        popularityprimitives_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        popularityprimitivesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
     */
    public Builder removePopularityprimitives(int index) {
      if (popularityprimitivesBuilder_ == null) {
        ensurePopularityprimitivesIsMutable();
        popularityprimitives_.remove(index);
        onChanged();
      } else {
        popularityprimitivesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
     */
    public proto.PopularityPrimitive.Builder getPopularityprimitivesBuilder(
        int index) {
      return getPopularityprimitivesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
     */
    public proto.PopularityPrimitiveOrBuilder getPopularityprimitivesOrBuilder(
        int index) {
      if (popularityprimitivesBuilder_ == null) {
        return popularityprimitives_.get(index);  } else {
        return popularityprimitivesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
     */
    public java.util.List<? extends proto.PopularityPrimitiveOrBuilder> 
         getPopularityprimitivesOrBuilderList() {
      if (popularityprimitivesBuilder_ != null) {
        return popularityprimitivesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(popularityprimitives_);
      }
    }
    /**
     * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
     */
    public proto.PopularityPrimitive.Builder addPopularityprimitivesBuilder() {
      return getPopularityprimitivesFieldBuilder().addBuilder(
          proto.PopularityPrimitive.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
     */
    public proto.PopularityPrimitive.Builder addPopularityprimitivesBuilder(
        int index) {
      return getPopularityprimitivesFieldBuilder().addBuilder(
          index, proto.PopularityPrimitive.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
     */
    public java.util.List<proto.PopularityPrimitive.Builder> 
         getPopularityprimitivesBuilderList() {
      return getPopularityprimitivesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        proto.PopularityPrimitive, proto.PopularityPrimitive.Builder, proto.PopularityPrimitiveOrBuilder> 
        getPopularityprimitivesFieldBuilder() {
      if (popularityprimitivesBuilder_ == null) {
        popularityprimitivesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            proto.PopularityPrimitive, proto.PopularityPrimitive.Builder, proto.PopularityPrimitiveOrBuilder>(
                popularityprimitives_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        popularityprimitives_ = null;
      }
      return popularityprimitivesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:proto.PopularityPrimitiveResult)
  }

  // @@protoc_insertion_point(class_scope:proto.PopularityPrimitiveResult)
  private static final proto.PopularityPrimitiveResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.PopularityPrimitiveResult();
  }

  public static proto.PopularityPrimitiveResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PopularityPrimitiveResult>
      PARSER = new com.google.protobuf.AbstractParser<PopularityPrimitiveResult>() {
    @java.lang.Override
    public PopularityPrimitiveResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PopularityPrimitiveResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PopularityPrimitiveResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.PopularityPrimitiveResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

