// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface PopularityPrimitiveResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.PopularityPrimitiveResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
   */
  java.util.List<proto.PopularityPrimitive> 
      getPopularityprimitivesList();
  /**
   * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
   */
  proto.PopularityPrimitive getPopularityprimitives(int index);
  /**
   * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
   */
  int getPopularityprimitivesCount();
  /**
   * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
   */
  java.util.List<? extends proto.PopularityPrimitiveOrBuilder> 
      getPopularityprimitivesOrBuilderList();
  /**
   * <code>repeated .proto.PopularityPrimitive popularityprimitives = 1;</code>
   */
  proto.PopularityPrimitiveOrBuilder getPopularityprimitivesOrBuilder(
      int index);
}
