// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

/**
 * Protobuf enum {@code proto.PopularitySourcePopularitySourceEnum}
 */
public enum PopularitySourcePopularitySourceEnum
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>POPULARITYSOURCE_POPULARITY_SOURCE_NULL = 0;</code>
   */
  POPULARITYSOURCE_POPULARITY_SOURCE_NULL(0),
  /**
   * <code>IGDB = 121;</code>
   */
  IGDB(121),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      PopularitySourcePopularitySourceEnum.class.getName());
  }
  /**
   * <code>POPULARITYSOURCE_POPULARITY_SOURCE_NULL = 0;</code>
   */
  public static final int POPULARITYSOURCE_POPULARITY_SOURCE_NULL_VALUE = 0;
  /**
   * <code>IGDB = 121;</code>
   */
  public static final int IGDB_VALUE = 121;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PopularitySourcePopularitySourceEnum valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PopularitySourcePopularitySourceEnum forNumber(int value) {
    switch (value) {
      case 0: return POPULARITYSOURCE_POPULARITY_SOURCE_NULL;
      case 121: return IGDB;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PopularitySourcePopularitySourceEnum>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PopularitySourcePopularitySourceEnum> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PopularitySourcePopularitySourceEnum>() {
          public PopularitySourcePopularitySourceEnum findValueByNumber(int number) {
            return PopularitySourcePopularitySourceEnum.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return proto.Igdbapi.getDescriptor().getEnumTypes().get(15);
  }

  private static final PopularitySourcePopularitySourceEnum[] VALUES = values();

  public static PopularitySourcePopularitySourceEnum valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PopularitySourcePopularitySourceEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:proto.PopularitySourcePopularitySourceEnum)
}

