// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

/**
 * Protobuf type {@code proto.PopularityTypeResult}
 */
public final class PopularityTypeResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:proto.PopularityTypeResult)
    PopularityTypeResultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      PopularityTypeResult.class.getName());
  }
  // Use PopularityTypeResult.newBuilder() to construct.
  private PopularityTypeResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PopularityTypeResult() {
    popularitytypes_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.Igdbapi.internal_static_proto_PopularityTypeResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.Igdbapi.internal_static_proto_PopularityTypeResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.PopularityTypeResult.class, proto.PopularityTypeResult.Builder.class);
  }

  public static final int POPULARITYTYPES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<proto.PopularityType> popularitytypes_;
  /**
   * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
   */
  @java.lang.Override
  public java.util.List<proto.PopularityType> getPopularitytypesList() {
    return popularitytypes_;
  }
  /**
   * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends proto.PopularityTypeOrBuilder> 
      getPopularitytypesOrBuilderList() {
    return popularitytypes_;
  }
  /**
   * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
   */
  @java.lang.Override
  public int getPopularitytypesCount() {
    return popularitytypes_.size();
  }
  /**
   * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
   */
  @java.lang.Override
  public proto.PopularityType getPopularitytypes(int index) {
    return popularitytypes_.get(index);
  }
  /**
   * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
   */
  @java.lang.Override
  public proto.PopularityTypeOrBuilder getPopularitytypesOrBuilder(
      int index) {
    return popularitytypes_.get(index);
  }

  public static proto.PopularityTypeResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.PopularityTypeResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.PopularityTypeResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.PopularityTypeResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.PopularityTypeResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.PopularityTypeResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.PopularityTypeResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static proto.PopularityTypeResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static proto.PopularityTypeResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static proto.PopularityTypeResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.PopularityTypeResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static proto.PopularityTypeResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.PopularityTypeResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.PopularityTypeResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.PopularityTypeResult)
      proto.PopularityTypeResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Igdbapi.internal_static_proto_PopularityTypeResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Igdbapi.internal_static_proto_PopularityTypeResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.PopularityTypeResult.class, proto.PopularityTypeResult.Builder.class);
    }

    // Construct using proto.PopularityTypeResult.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (popularitytypesBuilder_ == null) {
        popularitytypes_ = java.util.Collections.emptyList();
      } else {
        popularitytypes_ = null;
        popularitytypesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.Igdbapi.internal_static_proto_PopularityTypeResult_descriptor;
    }

    @java.lang.Override
    public proto.PopularityTypeResult getDefaultInstanceForType() {
      return proto.PopularityTypeResult.getDefaultInstance();
    }

    @java.lang.Override
    public proto.PopularityTypeResult build() {
      proto.PopularityTypeResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.PopularityTypeResult buildPartial() {
      proto.PopularityTypeResult result = new proto.PopularityTypeResult(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(proto.PopularityTypeResult result) {
      if (popularitytypesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          popularitytypes_ = java.util.Collections.unmodifiableList(popularitytypes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.popularitytypes_ = popularitytypes_;
      } else {
        result.popularitytypes_ = popularitytypesBuilder_.build();
      }
    }

    private void buildPartial0(proto.PopularityTypeResult result) {
      int from_bitField0_ = bitField0_;
    }

    private int bitField0_;

    private java.util.List<proto.PopularityType> popularitytypes_ =
      java.util.Collections.emptyList();
    private void ensurePopularitytypesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        popularitytypes_ = new java.util.ArrayList<proto.PopularityType>(popularitytypes_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        proto.PopularityType, proto.PopularityType.Builder, proto.PopularityTypeOrBuilder> popularitytypesBuilder_;

    /**
     * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
     */
    public java.util.List<proto.PopularityType> getPopularitytypesList() {
      if (popularitytypesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(popularitytypes_);
      } else {
        return popularitytypesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
     */
    public int getPopularitytypesCount() {
      if (popularitytypesBuilder_ == null) {
        return popularitytypes_.size();
      } else {
        return popularitytypesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
     */
    public proto.PopularityType getPopularitytypes(int index) {
      if (popularitytypesBuilder_ == null) {
        return popularitytypes_.get(index);
      } else {
        return popularitytypesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
     */
    public Builder setPopularitytypes(
        int index, proto.PopularityType value) {
      if (popularitytypesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePopularitytypesIsMutable();
        popularitytypes_.set(index, value);
        onChanged();
      } else {
        popularitytypesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
     */
    public Builder setPopularitytypes(
        int index, proto.PopularityType.Builder builderForValue) {
      if (popularitytypesBuilder_ == null) {
        ensurePopularitytypesIsMutable();
        popularitytypes_.set(index, builderForValue.build());
        onChanged();
      } else {
        popularitytypesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
     */
    public Builder addPopularitytypes(proto.PopularityType value) {
      if (popularitytypesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePopularitytypesIsMutable();
        popularitytypes_.add(value);
        onChanged();
      } else {
        popularitytypesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
     */
    public Builder addPopularitytypes(
        int index, proto.PopularityType value) {
      if (popularitytypesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePopularitytypesIsMutable();
        popularitytypes_.add(index, value);
        onChanged();
      } else {
        popularitytypesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
     */
    public Builder addPopularitytypes(
        proto.PopularityType.Builder builderForValue) {
      if (popularitytypesBuilder_ == null) {
        ensurePopularitytypesIsMutable();
        popularitytypes_.add(builderForValue.build());
        onChanged();
      } else {
        popularitytypesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
     */
    public Builder addPopularitytypes(
        int index, proto.PopularityType.Builder builderForValue) {
      if (popularitytypesBuilder_ == null) {
        ensurePopularitytypesIsMutable();
        popularitytypes_.add(index, builderForValue.build());
        onChanged();
      } else {
        popularitytypesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
     */
    public Builder addAllPopularitytypes(
        java.lang.Iterable<? extends proto.PopularityType> values) {
      if (popularitytypesBuilder_ == null) {
        ensurePopularitytypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, popularitytypes_);
        onChanged();
      } else {
        popularitytypesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
     */
    public Builder clearPopularitytypes() {
      if (popularitytypesBuilder_ == null) {
        popularitytypes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        popularitytypesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
     */
    public Builder removePopularitytypes(int index) {
      if (popularitytypesBuilder_ == null) {
        ensurePopularitytypesIsMutable();
        popularitytypes_.remove(index);
        onChanged();
      } else {
        popularitytypesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
     */
    public proto.PopularityType.Builder getPopularitytypesBuilder(
        int index) {
      return getPopularitytypesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
     */
    public proto.PopularityTypeOrBuilder getPopularitytypesOrBuilder(
        int index) {
      if (popularitytypesBuilder_ == null) {
        return popularitytypes_.get(index);  } else {
        return popularitytypesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
     */
    public java.util.List<? extends proto.PopularityTypeOrBuilder> 
         getPopularitytypesOrBuilderList() {
      if (popularitytypesBuilder_ != null) {
        return popularitytypesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(popularitytypes_);
      }
    }
    /**
     * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
     */
    public proto.PopularityType.Builder addPopularitytypesBuilder() {
      return getPopularitytypesFieldBuilder().addBuilder(
          proto.PopularityType.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
     */
    public proto.PopularityType.Builder addPopularitytypesBuilder(
        int index) {
      return getPopularitytypesFieldBuilder().addBuilder(
          index, proto.PopularityType.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
     */
    public java.util.List<proto.PopularityType.Builder> 
         getPopularitytypesBuilderList() {
      return getPopularitytypesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        proto.PopularityType, proto.PopularityType.Builder, proto.PopularityTypeOrBuilder> 
        getPopularitytypesFieldBuilder() {
      if (popularitytypesBuilder_ == null) {
        popularitytypesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            proto.PopularityType, proto.PopularityType.Builder, proto.PopularityTypeOrBuilder>(
                popularitytypes_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        popularitytypes_ = null;
      }
      return popularitytypesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:proto.PopularityTypeResult)
  }

  // @@protoc_insertion_point(class_scope:proto.PopularityTypeResult)
  private static final proto.PopularityTypeResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.PopularityTypeResult();
  }

  public static proto.PopularityTypeResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PopularityTypeResult>
      PARSER = new com.google.protobuf.AbstractParser<PopularityTypeResult>() {
    @java.lang.Override
    public PopularityTypeResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PopularityTypeResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PopularityTypeResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.PopularityTypeResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

