// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface PopularityPrimitiveOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.PopularityPrimitive)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>int32 game_id = 2;</code>
   * @return The gameId.
   */
  int getGameId();

  /**
   * <code>.proto.PopularityType popularity_type = 3;</code>
   * @return Whether the popularityType field is set.
   */
  boolean hasPopularityType();
  /**
   * <code>.proto.PopularityType popularity_type = 3;</code>
   * @return The popularityType.
   */
  proto.PopularityType getPopularityType();
  /**
   * <code>.proto.PopularityType popularity_type = 3;</code>
   */
  proto.PopularityTypeOrBuilder getPopularityTypeOrBuilder();

  /**
   * <code>.proto.PopularitySourcePopularitySourceEnum popularity_source = 4;</code>
   * @return The enum numeric value on the wire for popularitySource.
   */
  int getPopularitySourceValue();
  /**
   * <code>.proto.PopularitySourcePopularitySourceEnum popularity_source = 4;</code>
   * @return The popularitySource.
   */
  proto.PopularitySourcePopularitySourceEnum getPopularitySource();

  /**
   * <code>double value = 5;</code>
   * @return The value.
   */
  double getValue();

  /**
   * <code>.google.protobuf.Timestamp calculated_at = 6;</code>
   * @return Whether the calculatedAt field is set.
   */
  boolean hasCalculatedAt();
  /**
   * <code>.google.protobuf.Timestamp calculated_at = 6;</code>
   * @return The calculatedAt.
   */
  com.google.protobuf.Timestamp getCalculatedAt();
  /**
   * <code>.google.protobuf.Timestamp calculated_at = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCalculatedAtOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp created_at = 7;</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 7;</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 7;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp updated_at = 8;</code>
   * @return Whether the updatedAt field is set.
   */
  boolean hasUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updated_at = 8;</code>
   * @return The updatedAt.
   */
  com.google.protobuf.Timestamp getUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updated_at = 8;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();

  /**
   * <code>string checksum = 9;</code>
   * @return The checksum.
   */
  java.lang.String getChecksum();
  /**
   * <code>string checksum = 9;</code>
   * @return The bytes for checksum.
   */
  com.google.protobuf.ByteString
      getChecksumBytes();
}
