// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface PopularityTypeResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.PopularityTypeResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
   */
  java.util.List<proto.PopularityType> 
      getPopularitytypesList();
  /**
   * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
   */
  proto.PopularityType getPopularitytypes(int index);
  /**
   * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
   */
  int getPopularitytypesCount();
  /**
   * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
   */
  java.util.List<? extends proto.PopularityTypeOrBuilder> 
      getPopularitytypesOrBuilderList();
  /**
   * <code>repeated .proto.PopularityType popularitytypes = 1;</code>
   */
  proto.PopularityTypeOrBuilder getPopularitytypesOrBuilder(
      int index);
}
