// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

/**
 * Protobuf type {@code proto.PopularityPrimitive}
 */
public final class PopularityPrimitive extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:proto.PopularityPrimitive)
    PopularityPrimitiveOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      PopularityPrimitive.class.getName());
  }
  // Use PopularityPrimitive.newBuilder() to construct.
  private PopularityPrimitive(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PopularityPrimitive() {
    popularitySource_ = 0;
    checksum_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.Igdbapi.internal_static_proto_PopularityPrimitive_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.Igdbapi.internal_static_proto_PopularityPrimitive_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.PopularityPrimitive.class, proto.PopularityPrimitive.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_ = 0L;
  /**
   * <code>uint64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int GAME_ID_FIELD_NUMBER = 2;
  private int gameId_ = 0;
  /**
   * <code>int32 game_id = 2;</code>
   * @return The gameId.
   */
  @java.lang.Override
  public int getGameId() {
    return gameId_;
  }

  public static final int POPULARITY_TYPE_FIELD_NUMBER = 3;
  private proto.PopularityType popularityType_;
  /**
   * <code>.proto.PopularityType popularity_type = 3;</code>
   * @return Whether the popularityType field is set.
   */
  @java.lang.Override
  public boolean hasPopularityType() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.proto.PopularityType popularity_type = 3;</code>
   * @return The popularityType.
   */
  @java.lang.Override
  public proto.PopularityType getPopularityType() {
    return popularityType_ == null ? proto.PopularityType.getDefaultInstance() : popularityType_;
  }
  /**
   * <code>.proto.PopularityType popularity_type = 3;</code>
   */
  @java.lang.Override
  public proto.PopularityTypeOrBuilder getPopularityTypeOrBuilder() {
    return popularityType_ == null ? proto.PopularityType.getDefaultInstance() : popularityType_;
  }

  public static final int POPULARITY_SOURCE_FIELD_NUMBER = 4;
  private int popularitySource_ = 0;
  /**
   * <code>.proto.PopularitySourcePopularitySourceEnum popularity_source = 4;</code>
   * @return The enum numeric value on the wire for popularitySource.
   */
  @java.lang.Override public int getPopularitySourceValue() {
    return popularitySource_;
  }
  /**
   * <code>.proto.PopularitySourcePopularitySourceEnum popularity_source = 4;</code>
   * @return The popularitySource.
   */
  @java.lang.Override public proto.PopularitySourcePopularitySourceEnum getPopularitySource() {
    proto.PopularitySourcePopularitySourceEnum result = proto.PopularitySourcePopularitySourceEnum.forNumber(popularitySource_);
    return result == null ? proto.PopularitySourcePopularitySourceEnum.UNRECOGNIZED : result;
  }

  public static final int VALUE_FIELD_NUMBER = 5;
  private double value_ = 0D;
  /**
   * <code>double value = 5;</code>
   * @return The value.
   */
  @java.lang.Override
  public double getValue() {
    return value_;
  }

  public static final int CALCULATED_AT_FIELD_NUMBER = 6;
  private com.google.protobuf.Timestamp calculatedAt_;
  /**
   * <code>.google.protobuf.Timestamp calculated_at = 6;</code>
   * @return Whether the calculatedAt field is set.
   */
  @java.lang.Override
  public boolean hasCalculatedAt() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp calculated_at = 6;</code>
   * @return The calculatedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCalculatedAt() {
    return calculatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : calculatedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp calculated_at = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCalculatedAtOrBuilder() {
    return calculatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : calculatedAt_;
  }

  public static final int CREATED_AT_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp createdAt_;
  /**
   * <code>.google.protobuf.Timestamp created_at = 7;</code>
   * @return Whether the createdAt field is set.
   */
  @java.lang.Override
  public boolean hasCreatedAt() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 7;</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreatedAt() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 7;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }

  public static final int UPDATED_AT_FIELD_NUMBER = 8;
  private com.google.protobuf.Timestamp updatedAt_;
  /**
   * <code>.google.protobuf.Timestamp updated_at = 8;</code>
   * @return Whether the updatedAt field is set.
   */
  @java.lang.Override
  public boolean hasUpdatedAt() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp updated_at = 8;</code>
   * @return The updatedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getUpdatedAt() {
    return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp updated_at = 8;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
    return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
  }

  public static final int CHECKSUM_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object checksum_ = "";
  /**
   * <code>string checksum = 9;</code>
   * @return The checksum.
   */
  @java.lang.Override
  public java.lang.String getChecksum() {
    java.lang.Object ref = checksum_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      checksum_ = s;
      return s;
    }
  }
  /**
   * <code>string checksum = 9;</code>
   * @return The bytes for checksum.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChecksumBytes() {
    java.lang.Object ref = checksum_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      checksum_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static proto.PopularityPrimitive parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.PopularityPrimitive parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.PopularityPrimitive parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.PopularityPrimitive parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.PopularityPrimitive parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.PopularityPrimitive parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.PopularityPrimitive parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static proto.PopularityPrimitive parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static proto.PopularityPrimitive parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static proto.PopularityPrimitive parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.PopularityPrimitive parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static proto.PopularityPrimitive parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.PopularityPrimitive prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.PopularityPrimitive}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.PopularityPrimitive)
      proto.PopularityPrimitiveOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Igdbapi.internal_static_proto_PopularityPrimitive_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Igdbapi.internal_static_proto_PopularityPrimitive_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.PopularityPrimitive.class, proto.PopularityPrimitive.Builder.class);
    }

    // Construct using proto.PopularityPrimitive.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getPopularityTypeFieldBuilder();
        getCalculatedAtFieldBuilder();
        getCreatedAtFieldBuilder();
        getUpdatedAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0L;
      gameId_ = 0;
      popularityType_ = null;
      if (popularityTypeBuilder_ != null) {
        popularityTypeBuilder_.dispose();
        popularityTypeBuilder_ = null;
      }
      popularitySource_ = 0;
      value_ = 0D;
      calculatedAt_ = null;
      if (calculatedAtBuilder_ != null) {
        calculatedAtBuilder_.dispose();
        calculatedAtBuilder_ = null;
      }
      createdAt_ = null;
      if (createdAtBuilder_ != null) {
        createdAtBuilder_.dispose();
        createdAtBuilder_ = null;
      }
      updatedAt_ = null;
      if (updatedAtBuilder_ != null) {
        updatedAtBuilder_.dispose();
        updatedAtBuilder_ = null;
      }
      checksum_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.Igdbapi.internal_static_proto_PopularityPrimitive_descriptor;
    }

    @java.lang.Override
    public proto.PopularityPrimitive getDefaultInstanceForType() {
      return proto.PopularityPrimitive.getDefaultInstance();
    }

    @java.lang.Override
    public proto.PopularityPrimitive build() {
      proto.PopularityPrimitive result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.PopularityPrimitive buildPartial() {
      proto.PopularityPrimitive result = new proto.PopularityPrimitive(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(proto.PopularityPrimitive result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.gameId_ = gameId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.popularityType_ = popularityTypeBuilder_ == null
            ? popularityType_
            : popularityTypeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.popularitySource_ = popularitySource_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.value_ = value_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.calculatedAt_ = calculatedAtBuilder_ == null
            ? calculatedAt_
            : calculatedAtBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.createdAt_ = createdAtBuilder_ == null
            ? createdAt_
            : createdAtBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.updatedAt_ = updatedAtBuilder_ == null
            ? updatedAt_
            : updatedAtBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.checksum_ = checksum_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    private int bitField0_;

    private long id_ ;
    /**
     * <code>uint64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>uint64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private int gameId_ ;
    /**
     * <code>int32 game_id = 2;</code>
     * @return The gameId.
     */
    @java.lang.Override
    public int getGameId() {
      return gameId_;
    }
    /**
     * <code>int32 game_id = 2;</code>
     * @param value The gameId to set.
     * @return This builder for chaining.
     */
    public Builder setGameId(int value) {

      gameId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 game_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearGameId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      gameId_ = 0;
      onChanged();
      return this;
    }

    private proto.PopularityType popularityType_;
    private com.google.protobuf.SingleFieldBuilder<
        proto.PopularityType, proto.PopularityType.Builder, proto.PopularityTypeOrBuilder> popularityTypeBuilder_;
    /**
     * <code>.proto.PopularityType popularity_type = 3;</code>
     * @return Whether the popularityType field is set.
     */
    public boolean hasPopularityType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.proto.PopularityType popularity_type = 3;</code>
     * @return The popularityType.
     */
    public proto.PopularityType getPopularityType() {
      if (popularityTypeBuilder_ == null) {
        return popularityType_ == null ? proto.PopularityType.getDefaultInstance() : popularityType_;
      } else {
        return popularityTypeBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.PopularityType popularity_type = 3;</code>
     */
    public Builder setPopularityType(proto.PopularityType value) {
      if (popularityTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        popularityType_ = value;
      } else {
        popularityTypeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.PopularityType popularity_type = 3;</code>
     */
    public Builder setPopularityType(
        proto.PopularityType.Builder builderForValue) {
      if (popularityTypeBuilder_ == null) {
        popularityType_ = builderForValue.build();
      } else {
        popularityTypeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.PopularityType popularity_type = 3;</code>
     */
    public Builder mergePopularityType(proto.PopularityType value) {
      if (popularityTypeBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          popularityType_ != null &&
          popularityType_ != proto.PopularityType.getDefaultInstance()) {
          getPopularityTypeBuilder().mergeFrom(value);
        } else {
          popularityType_ = value;
        }
      } else {
        popularityTypeBuilder_.mergeFrom(value);
      }
      if (popularityType_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.proto.PopularityType popularity_type = 3;</code>
     */
    public Builder clearPopularityType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      popularityType_ = null;
      if (popularityTypeBuilder_ != null) {
        popularityTypeBuilder_.dispose();
        popularityTypeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.proto.PopularityType popularity_type = 3;</code>
     */
    public proto.PopularityType.Builder getPopularityTypeBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getPopularityTypeFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.PopularityType popularity_type = 3;</code>
     */
    public proto.PopularityTypeOrBuilder getPopularityTypeOrBuilder() {
      if (popularityTypeBuilder_ != null) {
        return popularityTypeBuilder_.getMessageOrBuilder();
      } else {
        return popularityType_ == null ?
            proto.PopularityType.getDefaultInstance() : popularityType_;
      }
    }
    /**
     * <code>.proto.PopularityType popularity_type = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        proto.PopularityType, proto.PopularityType.Builder, proto.PopularityTypeOrBuilder> 
        getPopularityTypeFieldBuilder() {
      if (popularityTypeBuilder_ == null) {
        popularityTypeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            proto.PopularityType, proto.PopularityType.Builder, proto.PopularityTypeOrBuilder>(
                getPopularityType(),
                getParentForChildren(),
                isClean());
        popularityType_ = null;
      }
      return popularityTypeBuilder_;
    }

    private int popularitySource_ = 0;
    /**
     * <code>.proto.PopularitySourcePopularitySourceEnum popularity_source = 4;</code>
     * @return The enum numeric value on the wire for popularitySource.
     */
    @java.lang.Override public int getPopularitySourceValue() {
      return popularitySource_;
    }
    /**
     * <code>.proto.PopularitySourcePopularitySourceEnum popularity_source = 4;</code>
     * @param value The enum numeric value on the wire for popularitySource to set.
     * @return This builder for chaining.
     */
    public Builder setPopularitySourceValue(int value) {
      popularitySource_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.PopularitySourcePopularitySourceEnum popularity_source = 4;</code>
     * @return The popularitySource.
     */
    @java.lang.Override
    public proto.PopularitySourcePopularitySourceEnum getPopularitySource() {
      proto.PopularitySourcePopularitySourceEnum result = proto.PopularitySourcePopularitySourceEnum.forNumber(popularitySource_);
      return result == null ? proto.PopularitySourcePopularitySourceEnum.UNRECOGNIZED : result;
    }
    /**
     * <code>.proto.PopularitySourcePopularitySourceEnum popularity_source = 4;</code>
     * @param value The popularitySource to set.
     * @return This builder for chaining.
     */
    public Builder setPopularitySource(proto.PopularitySourcePopularitySourceEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      popularitySource_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.proto.PopularitySourcePopularitySourceEnum popularity_source = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPopularitySource() {
      bitField0_ = (bitField0_ & ~0x00000008);
      popularitySource_ = 0;
      onChanged();
      return this;
    }

    private double value_ ;
    /**
     * <code>double value = 5;</code>
     * @return The value.
     */
    @java.lang.Override
    public double getValue() {
      return value_;
    }
    /**
     * <code>double value = 5;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(double value) {

      value_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>double value = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      bitField0_ = (bitField0_ & ~0x00000010);
      value_ = 0D;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp calculatedAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> calculatedAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp calculated_at = 6;</code>
     * @return Whether the calculatedAt field is set.
     */
    public boolean hasCalculatedAt() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp calculated_at = 6;</code>
     * @return The calculatedAt.
     */
    public com.google.protobuf.Timestamp getCalculatedAt() {
      if (calculatedAtBuilder_ == null) {
        return calculatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : calculatedAt_;
      } else {
        return calculatedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp calculated_at = 6;</code>
     */
    public Builder setCalculatedAt(com.google.protobuf.Timestamp value) {
      if (calculatedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        calculatedAt_ = value;
      } else {
        calculatedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp calculated_at = 6;</code>
     */
    public Builder setCalculatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (calculatedAtBuilder_ == null) {
        calculatedAt_ = builderForValue.build();
      } else {
        calculatedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp calculated_at = 6;</code>
     */
    public Builder mergeCalculatedAt(com.google.protobuf.Timestamp value) {
      if (calculatedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          calculatedAt_ != null &&
          calculatedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getCalculatedAtBuilder().mergeFrom(value);
        } else {
          calculatedAt_ = value;
        }
      } else {
        calculatedAtBuilder_.mergeFrom(value);
      }
      if (calculatedAt_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp calculated_at = 6;</code>
     */
    public Builder clearCalculatedAt() {
      bitField0_ = (bitField0_ & ~0x00000020);
      calculatedAt_ = null;
      if (calculatedAtBuilder_ != null) {
        calculatedAtBuilder_.dispose();
        calculatedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp calculated_at = 6;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCalculatedAtBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getCalculatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp calculated_at = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCalculatedAtOrBuilder() {
      if (calculatedAtBuilder_ != null) {
        return calculatedAtBuilder_.getMessageOrBuilder();
      } else {
        return calculatedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : calculatedAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp calculated_at = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCalculatedAtFieldBuilder() {
      if (calculatedAtBuilder_ == null) {
        calculatedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCalculatedAt(),
                getParentForChildren(),
                isClean());
        calculatedAt_ = null;
      }
      return calculatedAtBuilder_;
    }

    private com.google.protobuf.Timestamp createdAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp created_at = 7;</code>
     * @return Whether the createdAt field is set.
     */
    public boolean hasCreatedAt() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 7;</code>
     * @return The createdAt.
     */
    public com.google.protobuf.Timestamp getCreatedAt() {
      if (createdAtBuilder_ == null) {
        return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      } else {
        return createdAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 7;</code>
     */
    public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdAt_ = value;
      } else {
        createdAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 7;</code>
     */
    public Builder setCreatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdAtBuilder_ == null) {
        createdAt_ = builderForValue.build();
      } else {
        createdAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 7;</code>
     */
    public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          createdAt_ != null &&
          createdAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getCreatedAtBuilder().mergeFrom(value);
        } else {
          createdAt_ = value;
        }
      } else {
        createdAtBuilder_.mergeFrom(value);
      }
      if (createdAt_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 7;</code>
     */
    public Builder clearCreatedAt() {
      bitField0_ = (bitField0_ & ~0x00000040);
      createdAt_ = null;
      if (createdAtBuilder_ != null) {
        createdAtBuilder_.dispose();
        createdAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 7;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getCreatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 7;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      if (createdAtBuilder_ != null) {
        return createdAtBuilder_.getMessageOrBuilder();
      } else {
        return createdAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreatedAtFieldBuilder() {
      if (createdAtBuilder_ == null) {
        createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedAt(),
                getParentForChildren(),
                isClean());
        createdAt_ = null;
      }
      return createdAtBuilder_;
    }

    private com.google.protobuf.Timestamp updatedAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updatedAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp updated_at = 8;</code>
     * @return Whether the updatedAt field is set.
     */
    public boolean hasUpdatedAt() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 8;</code>
     * @return The updatedAt.
     */
    public com.google.protobuf.Timestamp getUpdatedAt() {
      if (updatedAtBuilder_ == null) {
        return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
      } else {
        return updatedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 8;</code>
     */
    public Builder setUpdatedAt(com.google.protobuf.Timestamp value) {
      if (updatedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updatedAt_ = value;
      } else {
        updatedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 8;</code>
     */
    public Builder setUpdatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (updatedAtBuilder_ == null) {
        updatedAt_ = builderForValue.build();
      } else {
        updatedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 8;</code>
     */
    public Builder mergeUpdatedAt(com.google.protobuf.Timestamp value) {
      if (updatedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          updatedAt_ != null &&
          updatedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getUpdatedAtBuilder().mergeFrom(value);
        } else {
          updatedAt_ = value;
        }
      } else {
        updatedAtBuilder_.mergeFrom(value);
      }
      if (updatedAt_ != null) {
        bitField0_ |= 0x00000080;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 8;</code>
     */
    public Builder clearUpdatedAt() {
      bitField0_ = (bitField0_ & ~0x00000080);
      updatedAt_ = null;
      if (updatedAtBuilder_ != null) {
        updatedAtBuilder_.dispose();
        updatedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 8;</code>
     */
    public com.google.protobuf.Timestamp.Builder getUpdatedAtBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getUpdatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 8;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
      if (updatedAtBuilder_ != null) {
        return updatedAtBuilder_.getMessageOrBuilder();
      } else {
        return updatedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getUpdatedAtFieldBuilder() {
      if (updatedAtBuilder_ == null) {
        updatedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getUpdatedAt(),
                getParentForChildren(),
                isClean());
        updatedAt_ = null;
      }
      return updatedAtBuilder_;
    }

    private java.lang.Object checksum_ = "";
    /**
     * <code>string checksum = 9;</code>
     * @return The checksum.
     */
    public java.lang.String getChecksum() {
      java.lang.Object ref = checksum_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        checksum_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string checksum = 9;</code>
     * @return The bytes for checksum.
     */
    public com.google.protobuf.ByteString
        getChecksumBytes() {
      java.lang.Object ref = checksum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        checksum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string checksum = 9;</code>
     * @param value The checksum to set.
     * @return This builder for chaining.
     */
    public Builder setChecksum(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      checksum_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string checksum = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearChecksum() {
      checksum_ = getDefaultInstance().getChecksum();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string checksum = 9;</code>
     * @param value The bytes for checksum to set.
     * @return This builder for chaining.
     */
    public Builder setChecksumBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      checksum_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:proto.PopularityPrimitive)
  }

  // @@protoc_insertion_point(class_scope:proto.PopularityPrimitive)
  private static final proto.PopularityPrimitive DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.PopularityPrimitive();
  }

  public static proto.PopularityPrimitive getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PopularityPrimitive>
      PARSER = new com.google.protobuf.AbstractParser<PopularityPrimitive>() {
    @java.lang.Override
    public PopularityPrimitive parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PopularityPrimitive> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PopularityPrimitive> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.PopularityPrimitive getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

