// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: igdbapi.proto
// Protobuf Java Version: 4.27.2

package proto;

public interface SearchResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.SearchResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.Search searches = 1;</code>
   */
  java.util.List<proto.Search> 
      getSearchesList();
  /**
   * <code>repeated .proto.Search searches = 1;</code>
   */
  proto.Search getSearches(int index);
  /**
   * <code>repeated .proto.Search searches = 1;</code>
   */
  int getSearchesCount();
  /**
   * <code>repeated .proto.Search searches = 1;</code>
   */
  java.util.List<? extends proto.SearchOrBuilder> 
      getSearchesOrBuilderList();
  /**
   * <code>repeated .proto.Search searches = 1;</code>
   */
  proto.SearchOrBuilder getSearchesOrBuilder(
      int index);
}
